# Generated by Django 5.0.14 on 2026-09-14 17:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('name', models.CharField(default='Academy Administrator', max_length=255)),
                ('role', models.CharField(default='Super Admin', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('course', models.CharField(max_length=255)),
                ('schedule', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='SavedPassword',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('category', models.CharField(default='Other', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saved_passwords',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_raw', models.CharField(blank=True, max_length=255, null=True)),
                ('phone2', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('map_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('logo_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('address_en', models.CharField(blank=True, max_length=500, null=True)),
                ('address_am', models.CharField(blank=True, max_length=500, null=True)),
                ('prices', models.JSONField(default=dict)),
                ('social', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='StudentComment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_comments',
            },
        ),
    ]
