# Generated by Django 5.0.14 on 2026-09-14 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_am', models.CharField(blank=True, default='', max_length=255)),
                ('tagline_en', models.CharField(blank=True, default='', max_length=255)),
                ('tagline_am', models.CharField(blank=True, default='', max_length=255)),
                ('desc_en', models.TextField(blank=True, default='')),
                ('desc_am', models.TextField(blank=True, default='')),
                ('long_en', models.TextField(blank=True, default='')),
                ('long_am', models.TextField(blank=True, default='')),
                ('learn_en', models.JSONField(default=list)),
                ('learn_am', models.JSONField(default=list)),
                ('tools', models.JSONField(default=list)),
                ('image', models.CharField(blank=True, default='', max_length=1000)),
                ('accent', models.CharField(default='from-sky-500 to-blue-700', max_length=255)),
                ('fee_etb', models.CharField(blank=True, default='', max_length=50)),
                ('popular', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
