# Generated by Django 5.0.14 on 2026-09-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sitesettings_phone_alt_sitesettings_working_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sat_hours_end',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sat_hours_start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sun_hours_end',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sun_hours_start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
