# Generated by Django 5.0.14 on 2026-09-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sitesettings_sat_hours_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
